
package lab6p2_alejandrocardona;

import javax.swing.DefaultComboBoxModel;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class MainUI extends javax.swing.JFrame {
    static ArrayList<Consola> Consolas = new ArrayList();
    static ArrayList<Juego> Juegos = new ArrayList();

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        String [] size = {"Pequeña", "Mediana", "Grande"};
//        DefaultComboBoxModel cb = (DefaultComboBoxModel) cbPortatil.getModel();
        cbPortatil.removeAllItems();
        for (String string : size) {
            cbPortatil.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PopUpModConsola = new javax.swing.JPopupMenu();
        VerJuegos = new javax.swing.JMenuItem();
        ModConsola = new javax.swing.JMenuItem();
        DelConsola = new javax.swing.JMenuItem();
        DialogJuegos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListadeJuegos = new javax.swing.JList<>();
        AddJuego = new javax.swing.JButton();
        DialogAddJuego = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JuegoDate = new com.toedter.calendar.JDateChooser();
        JuegoDesc = new javax.swing.JTextField();
        JuegoNombre = new javax.swing.JTextField();
        JuegoCantidad = new javax.swing.JTextField();
        JuegoPrecio = new javax.swing.JTextField();
        JuegoEstado = new javax.swing.JTextField();
        JuegoRentable = new javax.swing.JCheckBox();
        JuegoAgregado = new javax.swing.JCheckBox();
        Crear = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        crearPortatil = new javax.swing.JPanel();
        cbPortatil = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LabelIDPort = new javax.swing.JTextField();
        LabelFabPort = new javax.swing.JTextField();
        LabelPrecioPort = new javax.swing.JTextField();
        LabelBtrPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelModeloPort = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        LabelYrsPort = new javax.swing.JTextField();
        CheckBoxEstuchePort = new javax.swing.JCheckBox();
        BtnCrearPort = new javax.swing.JButton();
        crearEstacionaria = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        IDEst = new javax.swing.JTextField();
        FabEst = new javax.swing.JTextField();
        PrecioEst = new javax.swing.JTextField();
        ContrEst = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ModeloEst = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        YearsEst = new javax.swing.JTextField();
        BtnCrearEst = new javax.swing.JButton();
        ConEst = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        StorageEst = new javax.swing.JTextField();
        listarConsolas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableListConsolas = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        VerJuegos.setText("Ver Juegos");
        VerJuegos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerJuegosMouseClicked(evt);
            }
        });
        VerJuegos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerJuegosActionPerformed(evt);
            }
        });
        PopUpModConsola.add(VerJuegos);

        ModConsola.setText("Modificar Consola");
        ModConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModConsolaMouseClicked(evt);
            }
        });
        ModConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModConsolaActionPerformed(evt);
            }
        });
        PopUpModConsola.add(ModConsola);

        DelConsola.setText("Eliminar Consola");
        DelConsola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelConsolaMouseClicked(evt);
            }
        });
        DelConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelConsolaActionPerformed(evt);
            }
        });
        PopUpModConsola.add(DelConsola);

        ListadeJuegos.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(ListadeJuegos);

        AddJuego.setText("Añadir Juego");
        AddJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddJuegoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DialogJuegosLayout = new javax.swing.GroupLayout(DialogJuegos.getContentPane());
        DialogJuegos.getContentPane().setLayout(DialogJuegosLayout);
        DialogJuegosLayout.setHorizontalGroup(
            DialogJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogJuegosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(AddJuego)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        DialogJuegosLayout.setVerticalGroup(
            DialogJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogJuegosLayout.createSequentialGroup()
                .addGroup(DialogJuegosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogJuegosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DialogJuegosLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(AddJuego)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel16.setText("Nombre");

        jLabel17.setText("Descripcion");

        jLabel18.setText("Fecha");

        jLabel19.setText("Precio");

        jLabel20.setText("Estado");

        jLabel21.setText("Rentable");

        jLabel22.setText("Agregado");

        jLabel23.setText("Cantidad Disponible");

        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DialogAddJuegoLayout = new javax.swing.GroupLayout(DialogAddJuego.getContentPane());
        DialogAddJuego.getContentPane().setLayout(DialogAddJuegoLayout);
        DialogAddJuegoLayout.setHorizontalGroup(
            DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogAddJuegoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialogAddJuegoLayout.createSequentialGroup()
                        .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(120, 120, 120)
                        .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JuegoNombre)
                            .addComponent(JuegoDesc)
                            .addComponent(JuegoDate, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(JuegoPrecio)))
                    .addGroup(DialogAddJuegoLayout.createSequentialGroup()
                        .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(jLabel20))
                        .addGap(75, 75, 75)
                        .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JuegoEstado)
                            .addComponent(JuegoCantidad)
                            .addGroup(DialogAddJuegoLayout.createSequentialGroup()
                                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JuegoRentable)
                                    .addComponent(JuegoAgregado))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(115, 115, 115)
                .addComponent(Crear)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        DialogAddJuegoLayout.setVerticalGroup(
            DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogAddJuegoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JuegoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(JuegoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(JuegoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(JuegoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Crear))
                .addGap(17, 17, 17)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(JuegoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(JuegoRentable))
                .addGap(18, 18, 18)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(JuegoAgregado))
                .addGap(18, 18, 18)
                .addGroup(DialogAddJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(JuegoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        cbPortatil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Identificacion: ");

        jLabel2.setText("Años de Uso");

        jLabel3.setText("Precio");

        jLabel4.setText("Fabricante");

        LabelPrecioPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelPrecioPortActionPerformed(evt);
            }
        });

        jLabel5.setText("Tamaño de Pantalla");

        jLabel6.setText("Modelo");

        jLabel7.setText("Duracion de Bateria");

        CheckBoxEstuchePort.setText("Estuche");
        CheckBoxEstuchePort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxEstuchePortActionPerformed(evt);
            }
        });

        BtnCrearPort.setText("Crear");
        BtnCrearPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCrearPortMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearPortatilLayout = new javax.swing.GroupLayout(crearPortatil);
        crearPortatil.setLayout(crearPortatilLayout);
        crearPortatilLayout.setHorizontalGroup(
            crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearPortatilLayout.createSequentialGroup()
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearPortatilLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(crearPortatilLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(66, 66, 66)
                                .addComponent(LabelIDPort, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearPortatilLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(89, 89, 89)
                                .addComponent(LabelFabPort, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearPortatilLayout.createSequentialGroup()
                                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(crearPortatilLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(111, 111, 111)
                                        .addComponent(LabelPrecioPort, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearPortatilLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LabelYrsPort, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crearPortatilLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(103, 103, 103)
                                        .addComponent(LabelModeloPort)))
                                .addGap(54, 54, 54)
                                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crearPortatilLayout.createSequentialGroup()
                                        .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                        .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LabelBtrPort, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(crearPortatilLayout.createSequentialGroup()
                                        .addComponent(CheckBoxEstuchePort)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(crearPortatilLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(BtnCrearPort)))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        crearPortatilLayout.setVerticalGroup(
            crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearPortatilLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelIDPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LabelFabPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPortatil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(LabelYrsPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LabelPrecioPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(LabelBtrPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearPortatilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(LabelModeloPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckBoxEstuchePort))
                .addGap(51, 51, 51)
                .addComponent(BtnCrearPort)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Portatil", crearPortatil);

        jLabel8.setText("Identificacion: ");

        jLabel9.setText("Años de Uso");

        jLabel10.setText("Precio");

        jLabel11.setText("Fabricante");

        PrecioEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioEstActionPerformed(evt);
            }
        });

        jLabel12.setText("Tipo de Conexion");

        jLabel13.setText("Modelo");

        jLabel14.setText("Cantidad de Controles");

        BtnCrearEst.setText("Crear");
        BtnCrearEst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCrearEstMouseClicked(evt);
            }
        });

        jLabel15.setText("Almacenamiento");

        javax.swing.GroupLayout crearEstacionariaLayout = new javax.swing.GroupLayout(crearEstacionaria);
        crearEstacionaria.setLayout(crearEstacionariaLayout);
        crearEstacionariaLayout.setHorizontalGroup(
            crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearEstacionariaLayout.createSequentialGroup()
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearEstacionariaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(crearEstacionariaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(66, 66, 66)
                                .addComponent(IDEst, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearEstacionariaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(89, 89, 89)
                                .addComponent(FabEst, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearEstacionariaLayout.createSequentialGroup()
                                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(crearEstacionariaLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(111, 111, 111)
                                        .addComponent(PrecioEst, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, crearEstacionariaLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(YearsEst, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crearEstacionariaLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(103, 103, 103)
                                        .addComponent(ModeloEst)))
                                .addGap(54, 54, 54)
                                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ContrEst, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(ConEst)
                                    .addComponent(StorageEst)))))
                    .addGroup(crearEstacionariaLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(BtnCrearEst)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        crearEstacionariaLayout.setVerticalGroup(
            crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearEstacionariaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(IDEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(FabEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(YearsEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(StorageEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PrecioEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(ContrEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(crearEstacionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ModeloEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ConEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(BtnCrearEst)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Estacionaria", crearEstacionaria);

        TableListConsolas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Fabricante", "Años de Uso", "Precio", "Modelo", "Tamaño", "Bateria", "Estuche", "Cant. de Controles", "Almacenamiento", "Conexion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableListConsolas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableListConsolasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableListConsolas);

        javax.swing.GroupLayout listarConsolasLayout = new javax.swing.GroupLayout(listarConsolas);
        listarConsolas.setLayout(listarConsolasLayout);
        listarConsolasLayout.setHorizontalGroup(
            listarConsolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarConsolasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listarConsolasLayout.setVerticalGroup(
            listarConsolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listarConsolasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Consolas", listarConsolas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelPrecioPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelPrecioPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelPrecioPortActionPerformed

    private void CheckBoxEstuchePortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxEstuchePortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxEstuchePortActionPerformed

    private void BtnCrearPortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCrearPortMouseClicked
        // TODO add your handling code here:
        
        CrearPortatil();
        
        
        LabelIDPort.setText("");
        LabelFabPort.setText("");
        LabelYrsPort.setText("");
        LabelPrecioPort.setText("");
        LabelBtrPort.setText("");
        LabelModeloPort.setText("");
        
        JOptionPane.showMessageDialog(null, "Se ha ingresado de manera exitosa");
        
    }//GEN-LAST:event_BtnCrearPortMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        listConsolas();
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void PrecioEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioEstActionPerformed

    private void BtnCrearEstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCrearEstMouseClicked
        // TODO add your handling code here:
        crearEstacionaria();
        
        
        IDEst.setText("");
        FabEst.setText("");
        YearsEst.setText("");
        PrecioEst.setText("");
        ModeloEst.setText("");
        ContrEst.setText("");
        StorageEst.setText("");
        ConEst.setText("");
        
        JOptionPane.showMessageDialog(null, "Se ha ingresado de manera exitosa");
        
        
    }//GEN-LAST:event_BtnCrearEstMouseClicked

    private void TableListConsolasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableListConsolasMouseClicked
        // TODO add your handling code here:
        
        if(evt.isMetaDown()){
            
            PopUpModConsola.show(TableListConsolas, evt.getX(), evt.getY());
            
        }
        
    }//GEN-LAST:event_TableListConsolasMouseClicked

    private void DelConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelConsolaMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_DelConsolaMouseClicked

    private void VerJuegosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerJuegosMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_VerJuegosMouseClicked

    private void ModConsolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModConsolaMouseClicked
        // TODO add your handling code here:
        
       
        
    }//GEN-LAST:event_ModConsolaMouseClicked

    private void ModConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModConsolaActionPerformed
        // TODO add your handling code here:
        if(TableListConsolas.getSelectedRow()>=0){
            
            if(Consolas.get(TableListConsolas.getSelectedRow()) instanceof Portatil){
                
                String ID = JOptionPane.showInputDialog(TableListConsolas, "Ingrese el ID de la consola");;
                String fab = JOptionPane.showInputDialog("Ingrese el fabricante de la consola");
                int años = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los años de uso de la consola"));
                double precio = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el precio de la consola"));
                String modelo = JOptionPane.showInputDialog("Ingrese el modelo de la consola");
                String size = JOptionPane.showInputDialog("Ingrese el tamaño de la consola");
                int bateria = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de almacenamiento disponible en la cosoola"));
                
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setID(ID);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setFabricante(fab);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setYears(años);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setPrecio(precio);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setModelo(modelo);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setSize(size);
                ((Portatil)Consolas.get(TableListConsolas.getSelectedRow())).setBateria(bateria);
                
            }
            else{
                
                String ID = JOptionPane.showInputDialog(TableListConsolas, "Ingrese el ID de la consola");;
                String fab = JOptionPane.showInputDialog("Ingrese el fabricante de la consola");
                int años = Integer.parseInt(JOptionPane.showInputDialog("Ingrese los años de uso de la consola"));
                double precio = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el precio de la consola"));
                String modelo = JOptionPane.showInputDialog("Ingrese el modelo de la consola");
                int controles = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de controles de la consoola"));
                double storage = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la cantidad de almacenamiento disponible en la cosoola"));
                String conexion = JOptionPane.showInputDialog("Ingrese el tipo de conexion de la consola");
                Estacionaria temp = new Estacionaria(controles, storage, conexion, ID, fab, años, precio, modelo);
                
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setID(ID);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setFabricante(fab);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setYears(años);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setPrecio(precio);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setModelo(modelo);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setControles(controles);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setAlmacenamieneto(storage);
                ((Estacionaria)Consolas.get(TableListConsolas.getSelectedRow())).setConexion(conexion);
                
                
            }
            
        }
        else{
            
            JOptionPane.showMessageDialog(TableListConsolas, "No ha seleccionado una consola");
            
        }
    }//GEN-LAST:event_ModConsolaActionPerformed

    private void VerJuegosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerJuegosActionPerformed
        // TODO add your handling code here:
        
        DialogJuegos.pack();
        DialogJuegos.show();
        
        if(TableListConsolas.getSelectedRow()>= 0){
            
            ArrayList<Juego> temp = Consolas.get(TableListConsolas.getSelectedRow()).getJuegos();
                
            DefaultListModel dl = (DefaultListModel) ListadeJuegos.getModel();
                
            for (Juego juego : temp) {
                
                dl.addElement(temp);
                
            }
            
            ListadeJuegos.setModel(dl);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado una consola");
        }
        
    }//GEN-LAST:event_VerJuegosActionPerformed

    private void AddJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddJuegoMouseClicked
        // TODO add your handling code here:
        
        DialogAddJuego.pack();
        DialogAddJuego.show();
        
    }//GEN-LAST:event_AddJuegoMouseClicked

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:
        
        String nombre = JuegoNombre.getText();
        String descripcion = JuegoDesc.getText();
        Date fecha = JuegoDate.getDate();
        double precio = Double.parseDouble(JuegoPrecio.getText());
        String estado = JuegoEstado.getText();
        boolean rentable = JuegoRentable.isSelected();
        boolean agregado = JuegoAgregado.isSelected();
        int cantidad = Integer.parseInt(JuegoCantidad.getText());
        
        Juego SSBB = new Juego(nombre, descripcion, fecha, precio, estado, rentable, agregado);
        Consolas.get(TableListConsolas.getSelectedRow()).getJuegos().add(SSBB);
        
    }//GEN-LAST:event_CrearMouseClicked

    private void DelConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelConsolaActionPerformed
        // TODO add your handling code here:
        
        if(TableListConsolas.getSelectedRow() >= 0){
            
            Consolas.remove(TableListConsolas.getSelectedRow());
            
        }
        else{
            
            JOptionPane.showMessageDialog(null, "No ha seleccionado una consola");
            
        }
        
    }//GEN-LAST:event_DelConsolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
            
        });
        
        
        
    }
    private void CrearPortatil(){
        
        String ID = LabelIDPort.getText();
        String fab = LabelFabPort.getText();
        int años = Integer.parseInt(LabelYrsPort.getText());
        boolean estuche = CheckBoxEstuchePort.isSelected();
        double precio = Double.parseDouble(LabelPrecioPort.getText());
        int bateria = Integer.parseInt(LabelBtrPort.getText());
        String size = cbPortatil.getItemAt(cbPortatil.getSelectedIndex());
        String modelo = LabelModeloPort.getText();
        
        
        
        Portatil nds = new Portatil(size, bateria, estuche,ID, fab, años, precio, modelo);
        Consolas.add(nds);
        
    }
    
    private void crearEstacionaria(){
        
        String ID = IDEst.getText();
        String fab = FabEst.getText();
        int años = Integer.parseInt(YearsEst.getText());
        double precio = Double.parseDouble(PrecioEst.getText());
        String modelo = ModeloEst.getText();
        int controles = Integer.parseInt(ContrEst.getText());
        double storage = Double.parseDouble(StorageEst.getText());
        String conexion = ConEst.getText();
        
        Estacionaria ps5 = new Estacionaria(controles, storage, conexion, ID, fab, años, precio, modelo);
        Consolas.add(ps5);
        
    }
    
    private void listConsolas(){
        int cont = 0;
        
        for (Consola consoles : Consolas) {
            
            if(consoles instanceof Portatil){
                
                DefaultTableModel dt = (DefaultTableModel)TableListConsolas.getModel();
                
                dt.setValueAt(consoles.getID(), cont, 0);
                dt.setValueAt(consoles.getFabricante(), cont, 1);
                dt.setValueAt(consoles.getYears(), cont, 2);
                dt.setValueAt(consoles.getPrecio(), cont, 3);
                dt.setValueAt(consoles.getModelo(), cont, 4);
                dt.setValueAt((((Portatil) consoles).getSize()), cont, 5);
                dt.setValueAt((((Portatil) consoles).getBateria()), cont, 6);
                dt.setValueAt((((Portatil) consoles).isEstuche()), cont, 7);
                
                TableListConsolas.setModel(dt);
                
                
            }
            else{
                
                DefaultTableModel dt = (DefaultTableModel)TableListConsolas.getModel();
                
                dt.setValueAt(consoles.getID(), cont, 0);
                dt.setValueAt(consoles.getFabricante(), cont, 1);
                dt.setValueAt(consoles.getYears(), cont, 2);
                dt.setValueAt(consoles.getPrecio(), cont, 3);
                dt.setValueAt(consoles.getModelo(), cont, 4);
                
                dt.setValueAt((((Estacionaria)consoles).getControles()), cont, 8);
                dt.setValueAt((((Estacionaria)consoles).getAlmacenamieneto()), cont, 9);
                dt.setValueAt((((Estacionaria)consoles).getConexion()), cont, 10);
                TableListConsolas.setModel(dt); 
                
            }
            cont++;
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddJuego;
    private javax.swing.JButton BtnCrearEst;
    private javax.swing.JButton BtnCrearPort;
    private javax.swing.JCheckBox CheckBoxEstuchePort;
    private javax.swing.JTextField ConEst;
    private javax.swing.JTextField ContrEst;
    private javax.swing.JButton Crear;
    private javax.swing.JMenuItem DelConsola;
    private javax.swing.JDialog DialogAddJuego;
    private javax.swing.JDialog DialogJuegos;
    private javax.swing.JTextField FabEst;
    private javax.swing.JTextField IDEst;
    private javax.swing.JCheckBox JuegoAgregado;
    private javax.swing.JTextField JuegoCantidad;
    private com.toedter.calendar.JDateChooser JuegoDate;
    private javax.swing.JTextField JuegoDesc;
    private javax.swing.JTextField JuegoEstado;
    private javax.swing.JTextField JuegoNombre;
    private javax.swing.JTextField JuegoPrecio;
    private javax.swing.JCheckBox JuegoRentable;
    private javax.swing.JTextField LabelBtrPort;
    private javax.swing.JTextField LabelFabPort;
    private javax.swing.JTextField LabelIDPort;
    private javax.swing.JTextField LabelModeloPort;
    private javax.swing.JTextField LabelPrecioPort;
    private javax.swing.JTextField LabelYrsPort;
    private javax.swing.JList<String> ListadeJuegos;
    private javax.swing.JMenuItem ModConsola;
    private javax.swing.JTextField ModeloEst;
    private javax.swing.JPopupMenu PopUpModConsola;
    private javax.swing.JTextField PrecioEst;
    private javax.swing.JTextField StorageEst;
    private javax.swing.JTable TableListConsolas;
    private javax.swing.JMenuItem VerJuegos;
    private javax.swing.JTextField YearsEst;
    private javax.swing.JComboBox<String> cbPortatil;
    private javax.swing.JPanel crearEstacionaria;
    private javax.swing.JPanel crearPortatil;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel listarConsolas;
    // End of variables declaration//GEN-END:variables
}
